### PR TITLE
remove duplicate keys to avoid warning messages when launching the role

### PR DESCRIPTION
**Pull request by broferek**
We have this message when launching the role :

 [WARNING]: While constructing a mapping from /opt/ansible/common_roles/galaxy/galaxy_kapacitor/defaults/main.yml, line 2, column 1, found a duplicate dict key (kapacitor_http_auth_enabled). Using last defined value only.

 [WARNING]: While constructing a mapping from /opt/ansible/common_roles/galaxy/galaxy_kapacitor/defaults/main.yml, line 2, column 1, found a duplicate dict key (kapacitor_http_shared_secret). Using last defined value only.

I have removed duplicate keys from defaults and kept the good ones.

Regards,

Ludo

### CODE REVIEW

**Comment by broferek** [comment]
Fix variable typo and indentation in Readme.md as well

**Comment by broferek** [comment]
Hi guys,

any news about this pull request?

Thanks,

Ludo

**Comment by fajfer** [comment]
Can someone accept this? I had to fix this myself and I just wanted to make the identical pull request

**Comment by russorat** [comment]
@broferek wow sorry about this. we really dropped the ball here. If you want to sign the CLA, i'll get this merged: https://www.influxdata.com/legal/cla/

**Review by BondAnthony — APPROVED** [review]
@russorat this looks good.

**Comment by BondAnthony** [comment]
Hi @broferek we still need this readme update but it appears the variable change in `main.yml` was already completed. Would you be willing to rebase and sign the CLA?

**Comment by broferek** [comment]
Hi @BondAnthony 

I have signed the CLA and resolve the conflict.

I guess we're now fine to merge this.

**Pull request closed without merging**
